volumes:
  postgres_volume:

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine3.17
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: pkg/postgres/migrator.Dockerfile
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DB_HOST: postgres