// Code generated by mockery. DO NOT EDIT.

package repomocks

import (
	context "context"

	model "github.com/marktsarkov/test/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIrepo is an autogenerated mock type for the Irepo type
type MockIrepo struct {
	mock.Mock
}

type MockIrepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIrepo) EXPECT() *MockIrepo_Expecter {
	return &MockIrepo_Expecter{mock: &_m.Mock}
}

// CheckBalance provides a mock function with given fields: ctx, withdrawal
func (_m *MockIrepo) CheckBalance(ctx context.Context, withdrawal *model.Withdrawal) (int, error) {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for CheckBalance")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) (int, error)); ok {
		return rf(ctx, withdrawal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) int); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Withdrawal) error); ok {
		r1 = rf(ctx, withdrawal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrepo_CheckBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBalance'
type MockIrepo_CheckBalance_Call struct {
	*mock.Call
}

// CheckBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal *model.Withdrawal
func (_e *MockIrepo_Expecter) CheckBalance(ctx interface{}, withdrawal interface{}) *MockIrepo_CheckBalance_Call {
	return &MockIrepo_CheckBalance_Call{Call: _e.mock.On("CheckBalance", ctx, withdrawal)}
}

func (_c *MockIrepo_CheckBalance_Call) Run(run func(ctx context.Context, withdrawal *model.Withdrawal)) *MockIrepo_CheckBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdrawal))
	})
	return _c
}

func (_c *MockIrepo_CheckBalance_Call) Return(_a0 int, _a1 error) *MockIrepo_CheckBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrepo_CheckBalance_Call) RunAndReturn(run func(context.Context, *model.Withdrawal) (int, error)) *MockIrepo_CheckBalance_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIdempotency provides a mock function with given fields: ctx, withdrawal
func (_m *MockIrepo) CheckIdempotency(ctx context.Context, withdrawal *model.Withdrawal) ([]byte, error) {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for CheckIdempotency")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) ([]byte, error)); ok {
		return rf(ctx, withdrawal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) []byte); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Withdrawal) error); ok {
		r1 = rf(ctx, withdrawal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrepo_CheckIdempotency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIdempotency'
type MockIrepo_CheckIdempotency_Call struct {
	*mock.Call
}

// CheckIdempotency is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal *model.Withdrawal
func (_e *MockIrepo_Expecter) CheckIdempotency(ctx interface{}, withdrawal interface{}) *MockIrepo_CheckIdempotency_Call {
	return &MockIrepo_CheckIdempotency_Call{Call: _e.mock.On("CheckIdempotency", ctx, withdrawal)}
}

func (_c *MockIrepo_CheckIdempotency_Call) Run(run func(ctx context.Context, withdrawal *model.Withdrawal)) *MockIrepo_CheckIdempotency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdrawal))
	})
	return _c
}

func (_c *MockIrepo_CheckIdempotency_Call) Return(_a0 []byte, _a1 error) *MockIrepo_CheckIdempotency_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrepo_CheckIdempotency_Call) RunAndReturn(run func(context.Context, *model.Withdrawal) ([]byte, error)) *MockIrepo_CheckIdempotency_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmWithdrawal provides a mock function with given fields: ctx, operationID
func (_m *MockIrepo) ConfirmWithdrawal(ctx context.Context, operationID uuid.UUID) (*model.Withdrawal, error) {
	ret := _m.Called(ctx, operationID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmWithdrawal")
	}

	var r0 *model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Withdrawal, error)); ok {
		return rf(ctx, operationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Withdrawal); ok {
		r0 = rf(ctx, operationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, operationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrepo_ConfirmWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmWithdrawal'
type MockIrepo_ConfirmWithdrawal_Call struct {
	*mock.Call
}

// ConfirmWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - operationID uuid.UUID
func (_e *MockIrepo_Expecter) ConfirmWithdrawal(ctx interface{}, operationID interface{}) *MockIrepo_ConfirmWithdrawal_Call {
	return &MockIrepo_ConfirmWithdrawal_Call{Call: _e.mock.On("ConfirmWithdrawal", ctx, operationID)}
}

func (_c *MockIrepo_ConfirmWithdrawal_Call) Run(run func(ctx context.Context, operationID uuid.UUID)) *MockIrepo_ConfirmWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIrepo_ConfirmWithdrawal_Call) Return(_a0 *model.Withdrawal, _a1 error) *MockIrepo_ConfirmWithdrawal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrepo_ConfirmWithdrawal_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Withdrawal, error)) *MockIrepo_ConfirmWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithdrawal provides a mock function with given fields: ctx, withdrawal
func (_m *MockIrepo) CreateWithdrawal(ctx context.Context, withdrawal *model.Withdrawal) (*model.Withdrawal, error) {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithdrawal")
	}

	var r0 *model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) (*model.Withdrawal, error)); ok {
		return rf(ctx, withdrawal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) *model.Withdrawal); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Withdrawal) error); ok {
		r1 = rf(ctx, withdrawal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrepo_CreateWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithdrawal'
type MockIrepo_CreateWithdrawal_Call struct {
	*mock.Call
}

// CreateWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal *model.Withdrawal
func (_e *MockIrepo_Expecter) CreateWithdrawal(ctx interface{}, withdrawal interface{}) *MockIrepo_CreateWithdrawal_Call {
	return &MockIrepo_CreateWithdrawal_Call{Call: _e.mock.On("CreateWithdrawal", ctx, withdrawal)}
}

func (_c *MockIrepo_CreateWithdrawal_Call) Run(run func(ctx context.Context, withdrawal *model.Withdrawal)) *MockIrepo_CreateWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdrawal))
	})
	return _c
}

func (_c *MockIrepo_CreateWithdrawal_Call) Return(_a0 *model.Withdrawal, _a1 error) *MockIrepo_CreateWithdrawal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrepo_CreateWithdrawal_Call) RunAndReturn(run func(context.Context, *model.Withdrawal) (*model.Withdrawal, error)) *MockIrepo_CreateWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function with given fields: ctx, id
func (_m *MockIrepo) GetWithdrawals(ctx context.Context, id uuid.UUID) ([]model.Withdrawal, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Withdrawal, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Withdrawal); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrepo_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type MockIrepo_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIrepo_Expecter) GetWithdrawals(ctx interface{}, id interface{}) *MockIrepo_GetWithdrawals_Call {
	return &MockIrepo_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, id)}
}

func (_c *MockIrepo_GetWithdrawals_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIrepo_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIrepo_GetWithdrawals_Call) Return(_a0 []model.Withdrawal, _a1 error) *MockIrepo_GetWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrepo_GetWithdrawals_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Withdrawal, error)) *MockIrepo_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// LockIdempotency provides a mock function with given fields: ctx, key, userID
func (_m *MockIrepo) LockIdempotency(ctx context.Context, key uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, key, userID)

	if len(ret) == 0 {
		panic("no return value specified for LockIdempotency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, key, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrepo_LockIdempotency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockIdempotency'
type MockIrepo_LockIdempotency_Call struct {
	*mock.Call
}

// LockIdempotency is a helper method to define mock.On call
//   - ctx context.Context
//   - key uuid.UUID
//   - userID uuid.UUID
func (_e *MockIrepo_Expecter) LockIdempotency(ctx interface{}, key interface{}, userID interface{}) *MockIrepo_LockIdempotency_Call {
	return &MockIrepo_LockIdempotency_Call{Call: _e.mock.On("LockIdempotency", ctx, key, userID)}
}

func (_c *MockIrepo_LockIdempotency_Call) Run(run func(ctx context.Context, key uuid.UUID, userID uuid.UUID)) *MockIrepo_LockIdempotency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIrepo_LockIdempotency_Call) Return(_a0 error) *MockIrepo_LockIdempotency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrepo_LockIdempotency_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockIrepo_LockIdempotency_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLedger provides a mock function with given fields: ctx, operationID
func (_m *MockIrepo) SaveLedger(ctx context.Context, operationID uuid.UUID) error {
	ret := _m.Called(ctx, operationID)

	if len(ret) == 0 {
		panic("no return value specified for SaveLedger")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, operationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrepo_SaveLedger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLedger'
type MockIrepo_SaveLedger_Call struct {
	*mock.Call
}

// SaveLedger is a helper method to define mock.On call
//   - ctx context.Context
//   - operationID uuid.UUID
func (_e *MockIrepo_Expecter) SaveLedger(ctx interface{}, operationID interface{}) *MockIrepo_SaveLedger_Call {
	return &MockIrepo_SaveLedger_Call{Call: _e.mock.On("SaveLedger", ctx, operationID)}
}

func (_c *MockIrepo_SaveLedger_Call) Run(run func(ctx context.Context, operationID uuid.UUID)) *MockIrepo_SaveLedger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIrepo_SaveLedger_Call) Return(_a0 error) *MockIrepo_SaveLedger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrepo_SaveLedger_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIrepo_SaveLedger_Call {
	_c.Call.Return(run)
	return _c
}

// SaveResponse provides a mock function with given fields: ctx, response, withdrawal
func (_m *MockIrepo) SaveResponse(ctx context.Context, response []byte, withdrawal *model.Withdrawal) error {
	ret := _m.Called(ctx, response, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for SaveResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, *model.Withdrawal) error); ok {
		r0 = rf(ctx, response, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrepo_SaveResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveResponse'
type MockIrepo_SaveResponse_Call struct {
	*mock.Call
}

// SaveResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - response []byte
//   - withdrawal *model.Withdrawal
func (_e *MockIrepo_Expecter) SaveResponse(ctx interface{}, response interface{}, withdrawal interface{}) *MockIrepo_SaveResponse_Call {
	return &MockIrepo_SaveResponse_Call{Call: _e.mock.On("SaveResponse", ctx, response, withdrawal)}
}

func (_c *MockIrepo_SaveResponse_Call) Run(run func(ctx context.Context, response []byte, withdrawal *model.Withdrawal)) *MockIrepo_SaveResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(*model.Withdrawal))
	})
	return _c
}

func (_c *MockIrepo_SaveResponse_Call) Return(_a0 error) *MockIrepo_SaveResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrepo_SaveResponse_Call) RunAndReturn(run func(context.Context, []byte, *model.Withdrawal) error) *MockIrepo_SaveResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIrepo creates a new instance of MockIrepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIrepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIrepo {
	mock := &MockIrepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
